### ISSUE TITLE
Possible bugs on diffusion example?

### ISSUE THREAD

**Issue by cssndrx** [modal-labs/modal-examples#569] opened 2024-01-31 04:59 UTC
Not sure if I'm doing something wrong, but just trying to run these two examples as is using the latest code on `main` for the examples repo: 

1. https://modal.com/docs/examples/stable_diffusion_xl 

`modal deploy stable_diffusion_xl.py` and then visiting the website generates "modal-http: internal server error: user function failed with status Failure: NameError("name 'FastAPI' is not defined")"

2. https://modal.com/docs/examples/dreambooth_app 

`modal run dreambooth_app.py` generates     "ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library."

Apologies if I'm doing something wrong. Really excited to play with these cool examples!

**Comment by kning** [comment] 2024-02-08 17:36
hi @cssndrx thanks for reporting, i was also able to reproduce, looking into a fix now.

**Comment by kning** [comment] 2024-02-08 18:25
merged the fix for #1, but actually couldn't reproduce #2 for dreambooth, the app run completed fine for me. could you try again?

<img width="1275" alt="image" src="https://github.com/modal-labs/modal-examples/assets/1820651/900a8c05-0a74-4ca9-a089-67206c7b67b1">

**Comment by cssndrx** [comment] 2024-02-09 03:40
Aw thanks a ton @kning ! 

Yeah I'm still seeing the error with dreambooth. Here's the full trace. Fwiw I am able to do `from torchvision import transforms` locally - but it seems to be erroring when modal tries to call it. Is the error remote? 

cass@Evergrow-Cass modal-examples % modal run 06_gpu_and_ml/dreambooth/dreambooth_app.py
✓ Initialized. View run at https://modal.com/cssndrx/apps/ap-Azc1dViHI7EidYVSCPo4jb
✓ Created objects.
├── 🔨 Created mount 
│   /Users/cass/Documents/GitHub/modal-examples/06_gpu_and_ml/dreambooth/dreambooth_app.py
├── 🔨 Created train.
├── 🔨 Created Model.inference.
├── 🔨 Created mount /Users/cass/Documents/GitHub/modal-examples/06_gpu_and_ml/dreambooth/assets
└── 🔨 Created fastapi_app => https://cssndrx--example-dreambooth-app-fastapi-app-dev.modal.run
Images loaded.
tokenizer/vocab.json: 100%|██████████| 1.06M/1.06M [00:00<00:00, 6.04MB/s]tokenizer/vocab.json: 100%|██████████| 1.06M/1.06M [00:00<00:00, 5.96MB/s]
tokenizer/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 5.16MB/s]
tokenizer/special_tokens_map.json: 100%|██████████| 472/472 [00:00<00:00, 1.58MB/s]
tokenizer/tokenizer_config.json:   0%|          | 0.00/806 [00:00<?, ?B/s]tokenizer/tokenizer_config.json: 100%|██████████| 806/806 [00:00<00:00, 2.89MB/s]
launching dreambooth training script
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/examples/dreambooth/train_dreambooth.py:43 in <module>                 │
│                                                                              │
│    40 from diffusers.utils.import_utils import is_xformers_available         │
│    41 from huggingface_hub import HfFolder, Repository, whoami               │
│    42 from PIL import Image                                                  │
│ ❱  43 from torchvision import transforms                                     │
│    44 from tqdm.auto import tqdm                                             │
│    45 from transformers import AutoTokenizer, PretrainedConfig               │
│    46                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torchvision/__init__.py:6 in         │
│ <module>                                                                     │
│                                                                              │
│     3 from modulefinder import Module                                        │
│     4                                                                        │
│     5 import torch                                                           │
│ ❱   6 from torchvision import _meta_registrations, datasets, io, models, ops │
│     7                                                                        │
│     8 from .extension import _HAS_OPS                                        │
│     9                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torchvision/_meta_registrations.py:1 │
│ 64 in <module>                                                               │
│                                                                              │
│   161                                                                        │
│   162                                                                        │
│   163 @torch._custom_ops.impl_abstract("torchvision::nms")                   │
│ ❱ 164 def meta_nms(dets, scores, iou_threshold):                             │
│   165 │   torch._check(dets.dim() == 2, lambda: f"boxes should be a 2d tenso │
│   166 │   torch._check(dets.size(1) == 4, lambda: f"boxes should have 4 elem │
│   167 │   torch._check(scores.dim() == 1, lambda: f"scores should be a 1d te │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/_custom_ops.py:253 in inner    │
│                                                                              │
│   250 │   """                                                                │
│   251 │                                                                      │
│   252 │   def inner(func):                                                   │
│ ❱ 253 │   │   custom_op = _find_custom_op(qualname, also_check_torch_library │
│   254 │   │   custom_op.impl_abstract(_stacklevel=3)(func)                   │
│   255 │   │   return func                                                    │
│   256                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/_custom_op/impl.py:1076 in     │
│ _find_custom_op                                                              │
│                                                                              │
│   1073 │   │   raise RuntimeError(                                           │
│   1074 │   │   │   f"Could not find custom op \"{qualname}\". Did you regist │
│   1075 │   │   │   f"the torch._custom_ops API?")                            │
│ ❱ 1076 │   overload = get_op(qualname)                                       │
│   1077 │   result = custom_op_from_existing(overload)                        │
│   1078 │   return result                                                     │
│   1079                                                                       │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/_custom_op/impl.py:1062 in     │
│ get_op                                                                       │
│                                                                              │
│   1059 │   │   error_not_found()                                             │
│   1060 │   opnamespace = getattr(torch.ops, ns)                              │
│   1061 │   if not hasattr(opnamespace, name):                                │
│ ❱ 1062 │   │   error_not_found()                                             │
│   1063 │   packet = getattr(opnamespace, name)                               │
│   1064 │   if not hasattr(packet, 'default'):                                │
│   1065 │   │   error_not_found()                                             │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/torch/_custom_op/impl.py:1052 in     │
│ error_not_found                                                              │
│                                                                              │
│   1049                                                                       │
│   1050 def get_op(qualname):                                                 │
│   1051 │   def error_not_found():                                            │
│ ❱ 1052 │   │   raise ValueError(                                             │
│   1053 │   │   │   f"Could not find the operator {qualname}. Please make sur │
│   1054 │   │   │   f"already registered the operator and (if registered from │
│   1055 │   │   │   f"loaded it via torch.ops.load_library.")                 │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Could not find the operator torchvision::nms. Please make sure you 
have already registered the operator and (if registered from C++) loaded it via 
torch.ops.load_library.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/bin/accelerate:8 in <module>                                      │
│                                                                              │
│   5 from accelerate.commands.accelerate_cli import main                      │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.p │
│ y:45 in main                                                                 │
│                                                                              │
│   42 │   │   exit(1)                                                         │
│   43 │                                                                       │
│   44 │   # Run                                                               │
│ ❱ 45 │   args.func(args)                                                     │
│   46                                                                         │
│   47                                                                         │
│   48 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/accelerate/commands/launch.py:918 in │
│ launch_command                                                               │
│                                                                              │
│   915 │   elif defaults is not None and defaults.compute_environment == Comp │
│   916 │   │   sagemaker_launcher(defaults, args)                             │
│   917 │   else:                                                              │
│ ❱ 918 │   │   simple_launcher(args)                                          │
│   919                                                                        │
│   920                                                                        │
│   921 def main():                                                            │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/accelerate/commands/launch.py:580 in │
│ simple_launcher                                                              │
│                                                                              │
│   577 │   process.wait()                                                     │
│   578 │   if process.returncode != 0:                                        │
│   579 │   │   if not args.quiet:                                             │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.ret │
│   581 │   │   else:                                                          │
│   582 │   │   │   sys.exit(1)                                                │
│   583                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/usr/local/bin/python', 
'examples/dreambooth/train_dreambooth.py', '--train_text_encoder', 
'--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', 
'--instance_data_dir=/img', '--output_dir=/model', "--instance_prompt='a photo 
of Qwerty Golden Retriever'", '--resolution=512', '--train_batch_size=1', 
'--gradient_accumulation_steps=1', '--learning_rate=2e-06', 
'--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=600', 
'--checkpointing_steps=1000']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 372, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 530, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/dreambooth_app.py", line 234, in train
    _exec_subprocess(
  File "/root/dreambooth_app.py", line 230, in _exec_subprocess
    raise subprocess.CalledProcessError(exitcode, "\n".join(cmd))
subprocess.CalledProcessError: Command 'accelerate
launch
examples/dreambooth/train_dreambooth.py
--train_text_encoder
--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5
--instance_data_dir=/img
--output_dir=/model
--instance_prompt='a photo of Qwerty Golden Retriever'
--resolution=512
--train_batch_size=1
--gradient_accumulation_steps=1
--learning_rate=2e-06
--lr_scheduler=constant
--lr_warmup_steps=0
--max_train_steps=600
--checkpointing_steps=1000' returned non-zero exit status 1.
Stopping app - uncaught exception raised locally: CalledProcessError(True, "accelerate\nlaunch\nexamples/dreambooth/train_dreambooth.py\n--train_text_encoder\n--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5\n--instance_data_dir=/img\n--output_dir=/model\n--instance_prompt='a photo of Qwerty Golden Retriever'\n--resolution=512\n--train_batch_size=1\n--gradient_accumulation_steps=1\n--learning_rate=2e-06\n--lr_scheduler=constant\n--lr_warmup_steps=0\n--max_train_steps=600\n--checkpointing_steps=1000").
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/homebrew/bin/modal:8 in <module>                                                            │
│                                                                                                  │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/modal/__main__.py:9 in main                           │
│                                                                                                  │
│    8 │   setup_rich_traceback()                                                                  │
│ ❱  9 │   entrypoint_cli()                                                                        │
│   10                                                                                             │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/core.py:1157 in __call__                        │
│                                                                                                  │
│   1156 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1157 │   │   return self.main(*args, **kwargs)                                                 │
│   1158                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/typer/core.py:778 in main                             │
│                                                                                                  │
│   777 │   ) -> Any:                                                                              │
│ ❱ 778 │   │   return _main(                                                                      │
│   779 │   │   │   self,                                                                          │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/typer/core.py:216 in _main                            │
│                                                                                                  │
│   215 │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                       │
│ ❱ 216 │   │   │   │   rv = self.invoke(ctx)                                                      │
│   217 │   │   │   │   if not standalone_mode:                                                    │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/core.py:1688 in invoke                          │
│                                                                                                  │
│   1687 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1689                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/core.py:1688 in invoke                          │
│                                                                                                  │
│   1687 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1689                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/core.py:1434 in invoke                          │
│                                                                                                  │
│   1433 │   │   if self.callback is not None:                                                     │
│ ❱ 1434 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1435                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/core.py:783 in invoke                           │
│                                                                                                  │
│    782 │   │   │   with ctx:                                                                     │
│ ❱  783 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    784                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/click/decorators.py:33 in new_func                    │
│                                                                                                  │
│    32 │   def new_func(*args: "P.args", **kwargs: "P.kwargs") -> "R":                            │
│ ❱  33 │   │   return f(get_current_context(), *args, **kwargs)                                   │
│    34                                                                                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/modal/cli/run.py:187 in f                             │
│                                                                                                  │
│   186 │   │   │   else:                                                                          │
│ ❱ 187 │   │   │   │   func(*args, **kwargs)                                                      │
│   188                                                                                            │
│                                                                                                  │
│ /Users/cass/Documents/GitHub/modal-examples/06_gpu_and_ml/dreambooth/dreambooth_app.py:392 in    │
│ run                                                                                              │
│                                                                                                  │
│   391 │   │   instance_example_urls = [line.strip() for line in f.readlines()]                   │
│ ❱ 392 │   train.remote(instance_example_urls)                                                    │
│   393                                                                                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/synchronicity/synchronizer.py:509 in proxy_method     │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/synchronicity/combined_types.py:26 in __call__        │
│                                                                                                  │
│                 ...Remote call to Modal Function (ta-BBVBc6n9coOjVzRnOfG0VA)...                  │
│                                                                                                  │
│ /root/dreambooth_app.py:234 in train                                                             │
│                                                                                                  │
│ ❱ 234 _exec_subprocess(                                                                          │
│                                                                                                  │
│                                                                                                  │
│ /root/dreambooth_app.py:230 in _exec_subprocess                                                  │
│                                                                                                  │
│ ❱ 230 raise subprocess.CalledProcessError(exitcode, "\n".join(cmd))                              │
│                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command 'accelerate
launch
examples/dreambooth/train_dreambooth.py
--train_text_encoder
--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5
--instance_data_dir=/img
--output_dir=/model
--instance_prompt='a photo of Qwerty Golden Retriever'
--resolution=512
--train_batch_size=1
--gradient_accumulation_steps=1
--learning_rate=2e-06
--lr_scheduler=constant
--lr_warmup_steps=0
--max_train_steps=600
--checkpointing_steps=1000' returned non-zero exit status 1.
cass@Evergrow-Cass modal-examples % git tree                                            
cass@Evergrow-Cass modal-examples % python3
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from torchvision import transforms 
>>>

**Comment by kning** [comment] 2024-02-09 18:36
what happens if you upgrade torch and torchvision in the image:
```
"torch~=2.2",
"torchvision~=0.17"
```
testing that now as well

**Comment by kning** [comment] 2024-02-09 18:48
also which version of modal are you running? maybe worth a `pip install modal --upgrade`

**Comment by kning** [comment] 2024-02-14 21:17
closing this for now since wasn't able to reproduce dreambooth error

**Closed by kning** 2024-02-14 21:17 UTC
