### ISSUE TITLE
dockerfile has no stages and cannot be built

### ISSUE THREAD

**Issue by mhingston** [modal-labs/modal-examples#754] opened 2024-05-24 17:17 UTC
Hi,

I'm trying to run `06_gpu_and_ml/llm-serving/vllm_oai_compatible/api.py` but I get the following stack trace:

```
$ modal serve 06_gpu_and_ml/llm-serving/vllm_oai_compatible/api.py
✓ Initialized. View run at https://modal.com/mhingston/apps/ap-JV2bb6aEM0pRubsqRH0y5W
Building image im-3zEN08FSupbIqt1uUVYIlO

=> Step 0: running function 'download_model_to_image'
Building image im-3zEN08FSupbIqt1uUVYIlO
Terminating task due to error: dockerfile has no stages and cannot be built
Creating image snapshot...
Finished snapshot; took 17.30s
Finished image build for im-3zEN08FSupbIqt1uUVYIlO
```

**Comment by charlesfrye** [comment] 2024-05-25 14:57
Thanks for reporting. We're investigating.

In your error trace and in my reproduction script (below) the image build completes successfully and the `run_function` step finishes, so the written files are readable by downstream consumers of the image.

While we work on a resolution, could you confirm whether the rest of the example is working?

**Comment by charlesfrye** [comment] 2024-05-25 15:17
```python
import os

import modal


def f():
    with open("/test", "w") as f:
        f.write("hello from build time")


reader_image = modal.Image.debian_slim().run_function(f, force_build=True)

app = modal.App("no-stages")


@app.function(image=reader_image)
def go():
    with open("/test", "r") as f:
        print(f.read())
 ```

**Comment by mhingston** [comment] 2024-05-25 19:58
Hi @charlesfrye I had the same issue running your script above. I was able to resolve my issue my reinstalling modal with pip.

**Comment by charlesfrye** [comment] 2024-05-25 20:38
Actually, I'm pretty sure you're still experiencing the issue, but it's stochastic!

We believe we've determined the cause of the issue. In recent deployments of the core Modal infrastructure, there's a bug in the image building path involving `.run_function` that is masked by a race condition where one of the "happy paths" usually wins, resulting in the error state being missed or just being harmlessly logged to the terminal.

The vLLM example (and all others with `run_function`) should run to completion, except in the rare case where the race condition triggers an actual exception. In that case the current resolution is to re-execute, but we'll have a fix out very shortly (today or tomorrow).

Since this is being tracked internally and involves code outside this repo, I am closing this issue. If you'd like to be informed when the fix is deployed, let me know!

**Closed by charlesfrye** 2024-05-25 20:38 UTC

**Comment by charlesfrye** [comment] 2024-05-25 22:26
This is now fixed in prod.
