### ISSUE TITLE
Not able to upload app.py for streamlit example

### ISSUE THREAD

**Issue by AvisP** [modal-labs/modal-examples#819] opened 2024-07-23 04:38 UTC
I was trying to replicate the streamlit example as shown [here](https://github.com/modal-labs/modal-examples/tree/main/10_integrations/streamlit). But when I am starting the application using `modal serve serve_streamlit.py` it is giving the following error 

```
Runner failed with exception: RuntimeError('app.py not found! Place the script with your streamlit app in the same directory.')
Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 478, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 725, in main
    service = import_single_function_service(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_container_entrypoint.py", line 500, in import_single_function_service
    module = importlib.import_module(function_def.module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/serve_streamlit.py", line 46, in <module>
    raise RuntimeError(
RuntimeError: app.py not found! Place the script with your streamlit app in the same directory.
```

I checked the files of the running container but `app.py` is not there. I changed the variable `streamlit_script_local_path` to where the file is situated locally. Kindly assist in figuring out how to put the file in right place.

![image](https://github.com/user-attachments/assets/2f974edb-63cf-4854-acbb-59710b5b2c0c)

**Comment by charlesfrye** [comment] 2024-08-05 22:43
Hi there! Apologies for the delayed response.

It looks like our example code is still running, so closing this issue -- we use the issues tab here for handling problems with the code in the repo, not for other code. You can get help (much more quickly than here!) in the Modal user Slack, https://modal.com/slack

Hard to say exactly what the issue is, but generally that code will fail if you don't place your local streamlit app file in the same directory as the `serve_streamlit.py` file and name it `app.py`.

**Closed by charlesfrye** 2024-08-05 22:43 UTC
