### ISSUE TITLE
Dreambooth example is missing scheduler_config.json?

### ISSUE THREAD

**Issue by yosun** [modal-labs/modal-examples#550] opened 2024-01-16 12:01 UTC
- [x] `modal run dreambooth_app.py`
- [x] gradio url live
- [x] prompt sent...
- [ ] image returned

Error no file named scheduler_config.json found in directory /model.

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 346, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 510, in call_function_sync
    enter_res = enter_method()
  File "/root/dreambooth_app.py", line 281, in __enter__
    ddim = DDIMScheduler.from_pretrained(MODEL_DIR, subfolder="scheduler")
  File "/root/src/diffusers/schedulers/scheduling_utils.py", line 134, in from_pretrained
    config, kwargs = cls.load_config(
  File "/root/src/diffusers/configuration_utils.py", line 320, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory /model.
Runner failed with exception: OSError('Error no file named scheduler_config.json found in directory /model.')
```

**Comment by kning** [comment] 2024-02-09 18:59
just did `modal run dreambooth_app.py` and `modal serve dreambooth_app.py` and unable to reproduce. try upgrading your modal client? `pip install modal --upgrade`.

**Comment by yosun** [comment] 2024-02-10 08:52
updated and tried again

the endpoint seems to start when I do `modal run dreambooth_app.py` but error occurs  when i try to run inferencing - 

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 367, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 536, in call_function_sync
    enter_res = enter_method()
  File "/root/dreambooth_app.py", line 281, in __enter__
    ddim = DDIMScheduler.from_pretrained(MODEL_DIR, subfolder="scheduler")
  File "/root/src/diffusers/schedulers/scheduling_utils.py", line 134, in from_pretrained
    config, kwargs = cls.load_config(
  File "/root/src/diffusers/configuration_utils.py", line 320, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory /model.
Runner failed with exception: OSError('Error no file named scheduler_config.json found in directory /model.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/root/dreambooth_app.py", line 330, in go
    return Model().inference.remote(text, config)
  File "/pkg/synchronicity/synchronizer.py", line 526, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
   POST /run/predict -> 500 Internal Server Error  (duration: 9.19 s)
  File "/pkg/synchronicity/combined_types.py", line 28, in __call__
    raise uc_exc.exc from None
  File "<ta-JUrMMsy41CmnLzNwi3vVVG>:/root/dreambooth_app.py", line 281, in __enter__
  File "<ta-JUrMMsy41CmnLzNwi3vVVG>:/root/src/diffusers/schedulers/scheduling_utils.py", line 134, in from_pretrained
  File "<ta-JUrMMsy41CmnLzNwi3vVVG>:/root/src/diffusers/configuration_utils.py", line 320, in load_config
OSError: Error no file named scheduler_config.json found in directory /model.
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 367, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 536, in call_function_sync
    enter_res = enter_method()
  File "/root/dreambooth_app.py", line 281, in __enter__
    ddim = DDIMScheduler.from_pretrained(MODEL_DIR, subfolder="scheduler")
  File "/root/src/diffusers/schedulers/scheduling_utils.py", line 134, in from_pretrained
    config, kwargs = cls.load_config(
  File "/root/src/diffusers/configuration_utils.py", line 320, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory /model.

```

**Comment by yosun** [comment] 2024-02-10 08:56
logs btw https://modal.com/yosun/logs/ap-L6Lg17iuI6KYwuhD31xW06?taskId=ta-1cWgWcaZkasf28oTtWA2U3&inputId=in-oXFQN5RO5d0790OylbyEyo

**Comment by kning** [comment] 2024-02-14 21:26
hm, my guess is the model isn't being committed to the volume? try running this to train again:

`modal run dreambooth_app.py::stub.train`

and then afterwards maybe `modal volume ls dreambooth-finetuning-volume` to see if there's data there

**Comment by yosun** [comment] 2024-02-15 14:13
```
run dreambooth_app.py::stub.train 
Usage: modal run dreambooth_app.py::stub.train [OPTIONS]
Try 'modal run dreambooth_app.py::stub.train --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Missing option '--instance-example-urls'.
```

**Comment by kning** [comment] 2024-02-15 19:27
what is in your `instance_example_urls.txt`?

**Comment by kning** [comment] 2024-02-26 15:00
closing for now since having trouble reproducing

**Closed by kning** 2024-02-26 15:00 UTC
