### ISSUE TITLE
[Streamlit Demo]: Modal Deploy TypeError: ClientSession.__init__() got an unexpected keyword argument `max_line_size`

### ISSUE THREAD

**Issue by 100stacks** [modal-labs/modal-examples#764] opened 2024-06-10 18:10 UTC
Hi Modal peeps,

I'm really enjoying your product DX and UX!

I ran into a issue when attempting to run and deploy the [Run and share Streamlit apps demo](https://modal.com/docs/examples/serve_streamlit).

![image](https://github.com/modal-labs/modal-examples/assets/10120600/5cee51dc-a8c5-4859-a2a0-3720dafa5647)

## Modal Deploy error

When I try to deploy the app I get this error:

![image](https://github.com/modal-labs/modal-examples/assets/10120600/857dbc8a-780e-4189-acbf-17d5946632bd)

 ### Stack trace

```
✓ Initialized. View run at https://modal.com/100stacks/main/apps/ap-XXX
✓ Created objects.
├── 🔨 Created mount /home/projects/streamlit-modal-serverless/app.py
├── 🔨 Created mount /home/projects/streamlit-modal-serverless/streamlit_server.py
└── 🔨 Created run => https://100stacks--streamlit-modal-serverless-app-run-dev.modal.run
⚡️ Serving... hit Ctrl-C to stop!
└── Watching /home/projects/streamlit-modal-serverless.
*****************
Local path: /root/app.py
*****************
*****************
remote path: /root/app.py
*****************

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 492, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 351, in run_input_async
    async for value in res:
  File "/pkg/modal/_asgi.py", line 127, in fn
    app_task.result()  # consume/raise exceptions if there are any!
    ^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_asgi.py", line 321, in web_server_proxy_app
    session = aiohttp.ClientSession(
              ^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClientSession.__init__() got an unexpected keyword argument 'max_line_size'

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8000
  Network URL: http://172.20.180.2:8000
  External URL: http://3.145.11.73:8000

Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 492, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 351, in run_input_async
    async for value in res:
  File "/pkg/modal/_asgi.py", line 127, in fn
    app_task.result()  # consume/raise exceptions if there are any!
    ^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_asgi.py", line 321, in web_server_proxy_app
    session = aiohttp.ClientSession(
              ^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClientSession.__init__() got an unexpected keyword argument 'max_line_size'
exception calling callback for <Future at 0x7fcac88f2210 state=cancelled>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.11/asyncio/futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
exception calling callback for <Future at 0x7fcac8c37910 state=cancelled>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.11/asyncio/futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-29' coro=<aio_generator_output_task() done, defined at /pkg/synchronicity/async_wrap.py:27> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-17' coro=<aio_generator_output_task() running at /pkg/synchronicity/async_wrap.py:30> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()]>>
✓ App aborted. View run at https://modal.com/100stacks/main/apps/ap-XXX
Disconnecting from Modal - This will terminate your Modal app in a few seconds.

Stopping app - keyboard interrupt received. Use `modal run --detach` to prevent KeyboardInterrupts from killing apps.
✓ App completed. View run at https://modal.com/100stacks/main/apps/ap-XXX
```

## TypeError: ClientSession.__init__() got an unexpected keyword argument `max_line_size`

It appears to be a `TypeError`:

[                max_line_size=64 * 1024,  # 64 KiB
](https://github.com/modal-labs/modal-client/blob/d62fcf224ddee6ad332cf8f756be6912e6160f9e/modal/_asgi.py#L327)

## Local Streamlit Deploy

When I `streamlit run` locally, the app launches as expected.

```
streamlit run app.py
```

<img width="997" alt="streamlit-modal" src="https://github.com/modal-labs/modal-examples/assets/10120600/d91af216-9156-478a-99ce-c2632c861f3c">

## See my code...

I pushed a PR with my code:

https://github.com/100stacks/streamlit-modal-serverless/pull/1/files

Appreciate any tips!

**Comment by charlesfrye** [comment] 2024-06-11 22:01
Thanks for the kind words and the report!

I'm not able to recreate this issue. Based on the existence of [this issue](https://github.com/aio-libs/aiohttp/issues/7515), I would guess that it depends on the version of `aiohttp`. I'm running `3.9.5`.

**Comment by ekzhang** [comment] 2024-06-12 13:08
Duplicate of https://github.com/modal-labs/modal-client/issues/1884

**Closed by ekzhang** 2024-06-12 13:08 UTC
